# Generated by Django 3.0.8 on 2021-02-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('fromTime', models.DateTimeField()),
                ('toTime', models.DateTimeField()),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
