# Generated by Django 3.0.8 on 2021-02-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='details',
            new_name='detail',
        ),
    ]
